### ISSUE TITLE
[NOT AN ISSUE]

### ISSUE THREAD

**Issue by DomzyMonz** [BlueProgrammer212/NeuralChess#1]
Note: This isn't an issue. @BlueProgrammer212 after reading this, please resolve/delete it if possible.

Hi Blue! I would just like to know how I can contact you again, cuz you suddenly deleted your main discord account. Can you please contact me through any platform? Thank you!

- Domzy

**Comment by BlueProgrammer212** [comment]
Yeah I got termed, here ya go: .blueprogrammer212 (Discord updated the friend request system, so you can just copy and paste it.)
